export  const Jsondata = [
    {
    width: 940,
    height: 788,
    fonts: [],
    pages: [
      {
        id: "RMsrpryz1K",
        children: [
          {
            id: "BnvUuXlaHK",
            type: "text",
            x: 52.90291887370091,
            y: 155.71636332087337,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "REVIEW",
            placeholder: "",
            fontSize: 81.07076162333307,
            fontFamily: "Asset",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(240,152,8,1)",
            align: "center",
            width: 1006.0530964093035,
            height: 113.49906627266628,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.4,
            letterSpacing: 0,
          },
          {
            id: "B8jaHXmzfd",
            type: "text",
            x: 16.304247582602798,
            y: 86.25555784417129,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "REVIEW",
            placeholder: "",
            fontSize: 81.07076162333307,
            fontFamily: "Asset",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(240,152,8,1)",
            align: "center",
            width: 1079.2504389915007,
            height: 113.49906627266628,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.4,
            letterSpacing: 0,
          },
          {
            id: "HJv_IAn20e",
            type: "text",
            x: 11.922044251611837,
            y: 17.051413322398815,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "REVIEW",
            placeholder: "",
            fontSize: 81.07076162333307,
            fontFamily: "Asset",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(240,152,8,1)",
            align: "center",
            width: 1089.6521608725304,
            height: 113.49906627266628,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.4,
            letterSpacing: 0,
          },
          {
            id: "T6seoT3qBe",
            type: "image",
            x: 52.77755298156488,
            y: 99.82887279852397,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            width: 522.0446681705895,
            height: 608.9666446468543,
            src: "https://images.unsplash.com/photo-1584464457692-54516d705fe0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTY5OTZ8MHwxfHNlYXJjaHwzOXx8RklUTkVTUyUyMCUyMEJPWElORyUyMEZFTUFMRXxlbnwwfHx8fDE2MjI1MzIxMDc&ixlib=rb-1.2.1&q=80&w=1080",
            cropX: 0,
            cropY: 0,
            cropWidth: 0.9664629817346649,
            cropHeight: 0.7515879451782002,
            flipX: false,
            flipY: false,
            borderColor: "black",
            borderSize: 0,
          },
          {
            id: "QlA_rjqdai",
            type: "text",
            x: -7.797870737847461,
            y: -48.796400766966755,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "REVIEW",
            placeholder: "",
            fontSize: 81.30924325979785,
            fontFamily: "Asset",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(240,152,8,1)",
            align: "center",
            width: 1132.6505695253616,
            height: 113.83294056371699,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.4,
            letterSpacing: 0,
          },
          {
            id: "xH-ENHC1Gm",
            type: "text",
            x: 625.6780487804867,
            y: 462.3621179428568,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ",
            placeholder: "",
            fontSize: 31.55975418123872,
            fontFamily: "Abhaya Libre",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(255,255,255,1)",
            align: "right",
            width: 287.2514943266423,
            height: 151.48682006994585,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.2,
            letterSpacing: 0,
          },
          {
            id: "uR6V9fwITm",
            type: "text",
            x: 599.2237113962748,
            y: 404.31219512195105,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "CLIENT NAME",
            placeholder: "",
            fontSize: 41,
            fontFamily: "Abhaya Libre",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(209,91,7,1)",
            align: "right",
            width: 305.659215472983,
            height: 49.199999999999996,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.2,
            letterSpacing: 0,
          },
          {
            id: "0Sm06sD6ig",
            type: "svg",
            x: -7.797870737847424,
            y: 725.7808832990346,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 959.1414634146342,
            height: 117.32682926829054,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(14,1,24,1)" },
          },
          {
            id: "QaFjFH7yf7",
            type: "svg",
            x: 16.956371767132858,
            y: 32.28381778725354,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iMzAiIGZpbGw9InJnYigwLCAxNjEsIDI1NSkiIC8+PC9zdmc+",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 117.41236886182195,
            height: 117.41236886182195,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(224,84,11,1)" },
          },
          {
            id: "SEwU4IuF5O",
            type: "svg",
            x: 520.2593188167828,
            y: 564.5816655304537,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHBvbHlnb24gZmlsbD0icmdiKDAsIDE2MSwgMjU1KSIgcG9pbnRzPSIwIDAsIDYwIDYwLCAwIDYwIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 116.99433971979954,
            height: 116.99433971979941,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(224,67,4,1)" },
          },
          {
            id: "0iXcook0_7",
            type: "text",
            x: 527.6878048780487,
            y: 656.5321028112284,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "www.fitness.com",
            placeholder: "",
            fontSize: 28,
            fontFamily: "Abhaya Libre",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "rgba(250,157,5,1)",
            align: "center",
            width: 575.7073170931765,
            height: 33.6,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.2,
            letterSpacing: 0,
          },
        ],
        background: "rgba(28,4,49,1)",
      },
    ],
  },
  {
    width: 940,
    height: 788,
    fonts: [],
    pages: [
      {
        id: "_LRE2FHajV",
        children: [
          {
            id: "BP-ELIR7h6",
            type: "svg",
            x: 222.98536585365608,
            y: 79.72682926829349,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iMzAiIGZpbGw9InJnYigwLCAxNjEsIDI1NSkiIC8+PC9zdmc+",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 486.34146341463577,
            height: 440.2146341463364,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(221,164,116,1)" },
          },
          {
            id: "qh6uUFRKie",
            type: "svg",
            x: 222.98536585365738,
            y: 295.20113132701334,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 486.3414634146332,
            height: 361.4146341463394,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(221,164,116,1)" },
          },
          {
            id: "-xc5d2Qeqh",
            type: "svg",
            x: 55.59384580441225,
            y: 78.56829268292576,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iMzAiIGZpbGw9InJnYigwLCAxNjEsIDI1NSkiIC8+PC9zdmc+",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 172.25005663460723,
            height: 172.25005663460723,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(240,73,7,1)" },
          },
          {
            id: "Mk-qU0sWqy",
            type: "svg",
            x: 116.31707317073146,
            y: 82.19168763968361,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iMzAiIGZpbGw9InJnYigwLCAxNjEsIDI1NSkiIC8+PC9zdmc+",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 137.5912391895834,
            height: 137.5912391895834,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(253,223,194,1)" },
          },
          {
            id: "8o2OgR4j4m",
            type: "text",
            x: 115.83902437024267,
            y: 115.56097560975581,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "Never forget your purpose ",
            placeholder: "",
            fontSize: 100,
            fontFamily: "Adamina",
            fontStyle: "normal",
            fontWeight: "normal",
            textDecoration: "",
            fill: "black",
            align: "center",
            width: 746.7609756497583,
            height: 240,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.2,
            letterSpacing: 0,
          },
          {
            id: "cVUjcJ46iG",
            type: "svg",
            x: 367.1862981305111,
            y: 407.5894311693382,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iMzAiIGZpbGw9InJnYigwLCAxNjEsIDI1NSkiIC8+PC9zdmc+",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 209.93959886092588,
            height: 190.0279755226194,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(197,95,5,1)" },
          },
          {
            id: "wPdCHM7hb4",
            type: "svg",
            x: 367.18629813051155,
            y: 500.603479820335,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 209.93959886092483,
            height: 156.01228565301784,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(197,95,5,1)" },
          },
          {
            id: "2960OCU8NJ",
            type: "text",
            x: 331.6292682926776,
            y: 384.3902439024385,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            text: "in Life",
            placeholder: "",
            fontSize: 155,
            fontFamily: "Great Vibes",
            fontStyle: "normal",
            fontWeight: "bold",
            textDecoration: "",
            fill: "black",
            align: "center",
            width: 592.4671390681954,
            height: 186,
            strokeWidth: 0,
            stroke: "black",
            lineHeight: 1.2,
            letterSpacing: 0,
          },
          {
            id: "n0u8c2-p3j",
            type: "svg",
            x: 210.45865581560722,
            y: 670.7170731707171,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 513.2807864968537,
            height: 6.961116365515447,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(238,150,5,1)" },
          },
          {
            id: "zyA6gxypPl",
            type: "svg",
            x: 179.79923054223096,
            y: 687.7170731707137,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 576.870884537232,
            height: 7.823525564922164,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(238,150,5,1)" },
          },
          {
            id: "IprX9EDH7y",
            type: "svg",
            x: 144.28867279040827,
            y: 705.7170731707116,
            rotation: 0,
            opacity: 1,
            locked: false,
            blurEnabled: false,
            blurRadius: 10,
            brightnessEnabled: false,
            brightness: 0,
            sepiaEnabled: false,
            grayscaleEnabled: false,
            shadowEnabled: false,
            shadowBlur: 5,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowColor: "black",
            src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
            cropX: 0,
            cropY: 0,
            cropWidth: 1,
            cropHeight: 1,
            keepRatio: false,
            flipX: false,
            flipY: false,
            width: 640.3453799273399,
            height: 8.684366960659105,
            borderColor: "black",
            borderSize: 0,
            colorsReplace: { "rgb(0, 161, 255)": "rgba(238,150,5,1)" },
          },
        ],
        background: "rgba(253,223,194,1)",
      },
    ],
  }
]